### ISSUE TITLE
rudalle==1.1.0rc0 gives TypeError: forward() got an unexpected keyword argument 'has_cache'

### ISSUE THREAD

**Issue by nerdyrodent** [shonenkov-AI/rudalle-aspect-ratio#2]
Just tested with rudalle==1.1.0rc0, but this gives ```TypeError: forward() got an unexpected keyword argument 'has_cache'```
Works great with 1.0.0 though :)

**Comment by RyPoints** [comment]
@nerdyrodent Thanks for this.  Encountered the same.

**Comment by shonenkov** [comment]
solved with version rudalle==1.1.1 here : https://github.com/shonenkov-AI/rudalle-aspect-ratio/pull/4
